web:
  build: .
  command: 'crystal run src/app.cr"'
  working_dir: /app/user
  environment:
    PORT: 3000
    DATABASE_URL: 'postgres://postgres:@herokuPostgresql:5432/postgres'
  ports:
    - '80:3000'
  links:
    - herokuPostgresql
  volumes:
    - '.:/app/user'
shell:
  build: .
  command: bash
  working_dir: /app/user
  environment:
    PORT: 3000
    DATABASE_URL: 'postgres://postgres:@herokuPostgresql:5432/postgres'
  ports:
    - '80:3000'
  links:
    - herokuPostgresql
  volumes:
    - '.:/app/user'
herokuPostgresql:
  image: postgres
