web:
  build: .
  command: "crystal run src/app.cr"
  working_dir: /app/user
  environment:
    DATABASE_URL: 'postgres://postgres:@db:5432/postgres'
  ports:
    - '80:3000'
  links:
    - db
  volumes:
    - '.:/app/user'
shell:
  build: .
  command: bash
  working_dir: /app/user
  environment:
    DATABASE_URL: 'postgres://postgres:@db:5432/postgres'
  ports:
    - '80:3000'
  links:
    - db
  volumes:
    - '.:/app/user'
db:
  image: postgres
